---
title: "Desafío 1: Leer una base de datos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

El objetivo de este desafío es que armes un proyecto y que leas una archivo de datos para aplicar lo que aprendas en el resto del curso. 


### 1. Creá un proyecto de RStudio

Si te olvidaste cómo se hace, revisa [esta sección](02-proyectos.html). Asegurate de usar un nombre descriptivo, asociado a los datos o el análisis que tenés en mente. 

### 2. Decidí que datos usar

Buscá algún set de datos que hayas usado para algo o quieras usar. Puede ser en formato .csv o de Excel. Guardalo en una carpeta llamada "datos" dentro de la carpeta de tu proyecto.

### 3. Lee los datos en R 

Creá un archivo de RMarkdown (por las dudas, [esta es la sección asociada](03-reportes-I.html)). Además de un título informativo, describí los datos con tus palabras. ¿Cuál es la fuente? ¿Qué variables incluyen? Armá un *chunk* para leer los datos (podés revisar [esta sección](04-lectura.html) y mostralos. ¿Cuántas obervaciones tiene? ¿Qué tipo de datos tiene cada columna?  

### 4. Generá nuevas columnas

Es posible que necesites alguna nueva variable, por ejemplo la suma entre otras dos columnas para calcular un total o la diferencia entre otras dos. La clave será usar la función `mutate()` (como viste en [esta sección](05-dplyr.html#Creando_nuevas_columnas_con_mutate())) y ya que estamos aplicá otro verbo de {dplyr} para seleccionar esas nuevas columnas y mostrarlas (fijate [acá](05-dplyr.html#Seleccionando_columnas_con_select()) si necesitás refrescar la memoria).

Hacé cada operación en un *chunk* separado explicando en el texto qué hace cada paso, por qué y qué esperás encontrar.

### 5. Resumen de datos

Ahora calculá un promedio o determiná el valor máximo o mínimo de alguna columna usando `summarise()`. Si tu base de datos tiene alguna variable con categorías, también probá hacer los mismos cálculos pero agrupando las observaciones (viste esto [en esta sección](05-dplyr.html#Agrupando_y_reduciendo_con_group_by()_%%_summarise())).

Podés analizar los datos tanto como se te ocurra, la idea es que te familiarices con los verbos de {dplyr} al mismo tiempo que sacas información de la base de datos que estás utilizando. 